### ISSUE TITLE
add coveralls to repo

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/pouchdb-hoodie-sync#22]
https://coveralls.io/

**Comment by janl** [comment]
@rgr2m How does this work? hoodie-plugin-api doesn’t have a `.coveralls.yml` file which we need according to the coverall docs. I don’t get how this works.

**Comment by christophwitzko** [comment]
I have used coveralls.io only with this tool: https://github.com/cainus/node-coveralls
hope it helps :smiley:

**Comment by janl** [comment]
@christophwitzko thanks! This looks nice, but I still don’t understand where `hoodie-plugin-api` configures any repo tokens and whatever else is necessary to hook this up :)

**Comment by gr2m** [comment]
when you create an account on https://coveralls.io/, you can create the repo for hoodiehq/pouchdb-hoodie-sync, and then get ENV variables, that can directly be set on Travis configs for the repo
