### ISSUE TITLE
add deploydocs command

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-sync#32]
see https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/package.json#L28-L31

**Comment by gr2m** [comment]
once docs are deployed, set URL at https://github.com/hoodiehq/pouchdb-hoodie-sync, seehttps://github.com/hoodiehq/pouchdb-hoodie-api

**Comment by lewiscowper** [comment]
Do you mean set URL to http://hoodiehq.github.io/pouchdb-hoodie-sync?

So should we build the docs before we deploy them? Or just add the gh-pages-deploy stuff?

**Comment by gr2m** [comment]
> Do you mean set URL to http://hoodiehq.github.io/pouchdb-hoodie-sync?

yes :) Once they are online

> Should we build the docs automatically before we deploy them

see https://github.com/hoodiehq/pouchdb-hoodie-sync/issues/34 :) Coordinate with @zoepage
