### ISSUE TITLE
run docs & deploydocs in postpublish

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-sync#34]

**Comment by lewiscowper** [comment]
This should actually work if #35 is merged. The code to do the deployment (1) is already running in Travis, but the `deploydocs` command just isn't defined, but the build docs command is running in Travis already.

They went in in this commit -> adeb07b9e00034b29d1f4294579954e1916a414a and the appropriate lines are here https://github.com/hoodiehq/pouchdb-hoodie-sync/blob/master/.travis.yml#L29-L31

**Comment by zoepage** [comment]
@gr2m feel free to merge, if you'd like to <3

**Comment by gr2m** [comment]
awesome, merged :ok_hand:
