### ISSUE TITLE
unpublish version 0.0.0-semantically-released

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-sync#38]
for some reason, the `0.0.0-semantically-released` was published, ooops. Problem is here: https://travis-ci.org/hoodiehq/pouchdb-hoodie-sync/jobs/67043781#L387

@zoepage can you please add me to the npm package?

We need to run this
`npm unpublish pouchdb-hoodie-sync@0.0.0-semantically-released`

And then, we have to double check the npm API key here: https://github.com/hoodiehq/pouchdb-hoodie-sync/blob/master/.travis.yml#L50. I'm quite sure it's not correct, and that's what causing the trouble

**Comment by zoepage** [comment]
okay, the version is set to `1.0.0`.
I've added you to the pkg.

I'll check the key.

**Comment by gr2m** [comment]
@boennemann we checked together that the API key is correct, that cannot be the cause, must be something else. For some reason, it doesn't know that 1.0.0 is already out, and tries to re-publish it. There were only `chore` commits after 1.0.0 anyway, it shouldn't publish at all

**Comment by boennemann** [comment]
Can you pin semantic-release@3.3.2 for now? There seems to be a bug somewhere in the pulling info from the registry part :/ I'm sorry. https://github.com/boennemann/semantic-release/issues/46

**Comment by zoepage** [comment]
Will do. Thanks!

**Comment by zoepage** [comment]
tried. failed.
https://travis-ci.org/hoodiehq/pouchdb-hoodie-sync/jobs/68371806#L389

added you @boennemann to the pkg.

**Comment by boennemann** [comment]
I'm on my way home to Munich till tomorrow 5pm, so I probably won't be able to look into it till then. Maybe @christophwitzko can help? :)

**Comment by boennemann** [comment]
Alright, got some time for trying some quick fixes in the meantime. Let's see how it goes.

**Comment by boennemann** [comment]
I had to [pin 3.3.2](https://github.com/hoodiehq/pouchdb-hoodie-sync/commit/7fef1e2b5b5f808267162171bc3f7825d65c1a37) and now we're back to normal: https://travis-ci.org/hoodiehq/pouchdb-hoodie-sync/jobs/68404030#L383

Meanwhile I've moved the latest tag on semantic-release back to 3.3.2, so the problematic version won't get installed until we've got this figured out. 

Sorry.
