### ISSUE TITLE
run `istanbul-coveralls` in `after_success`

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-sync#39]
Because coveralls tends to be down, and we don't want our builds to be blocked by it anymore. See https://github.com/hoodiehq/pouchdb-hoodie-api/commit/4dcdefe43a5da53622ee1735860e749429e5cc74.

**Comment by zoepage** [comment]
This is done or am I missing something?
https://github.com/hoodiehq/pouchdb-hoodie-sync/blob/master/.travis.yml
https://github.com/hoodiehq/pouchdb-hoodie-api/commit/4dcdefe43a5da53622ee1735860e749429e5cc74

**Comment by gr2m** [comment]
yes, it is :)

**Comment by zoepage** [comment]
Awesome :)
