### ISSUE TITLE
remove uuid usage from tests/utils/db.js

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-sync#40]
instead of https://github.com/hoodiehq/pouchdb-hoodie-sync/blob/master/tests/utils/db.js#L11, we can do https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/tests/utils/db.js#L14

For more context, see https://github.com/hoodiehq/pouchdb-hoodie-api/pull/37.

**Comment by nickcolley** [comment]
I'm going to give this a pop

**Comment by nickcolley** [comment]
https://github.com/hoodiehq/pouchdb-hoodie-sync/pull/52

**Comment by gr2m** [comment]
done via https://github.com/hoodiehq/pouchdb-hoodie-sync/commit/191d7535bea7005f0e12167a6e939f1ba0f0c193 :v:
