### ISSUE TITLE
add .clear() method

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/pouchdb-hoodie-sync#41]

**Comment by zoepage** [comment]
great starter issue here. maybe interesting for you @toh82 ?

**Comment by gr2m** [comment]
@zoepage did you mean the `.clear()` method for pouchdb-hoodie-api? https://github.com/hoodiehq/pouchdb-hoodie-api/issues/39

There is no clear method on pouchdb-hoodie-sync, is it?

**Comment by zoepage** [comment]
This was the question once. As we spoke, you said there is ;)

**Comment by gr2m** [comment]
Wow, I tend to forget stuff, I'm sorry :)

I really can't think of a use case for a clear method for pouchdb-hoodie-sync, what would it do? I'd suggest we close this issue, and if we find a use case, open it up again

**Comment by zoepage** [comment]
No worries. Sounds good to me :)
