### ISSUE TITLE
on('pull') / on('push')

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/pouchdb-hoodie-sync#8]
- [x] implement on()
- [x] ':pull'
- [x] ':push'

##### testing

**Comment by gr2m** [comment]
for of pull / push, make sure to create tests for both that do all the 3: `.push`, `.pull`, `.sync`. 

`"push"` events should never be triggered when doing `.pull()`, and vice versa

**Comment by zoepage** [comment]
:+1:
